version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=base_db
      - POSTGRES_USER=base_user
      - POSTGRES_PASSWORD=base_pass
    ports:
      - "5400:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8008
    ports:
      - "8008:8000"
    depends_on:
      - db